name: ML_pro1
channels:
  - defaults
prefix:
  - numpy=1.15.4
  - matplotlib-base=3.1.1
  - sklearn=0.21.3
  - jupyter_client=5.3.1
  - jupyter_core=4.4.0
  - jupyterlab=1.1.3
  - jupyterlab_server=1.0.6
